# NumPy

NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are alreay familiar with Matlab, you might find this [tutorial](http://scipy.github.io/old-wiki/pages/NumPy_for_Matlab_Users) useful to get started with Numpy.

In some ways, NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data or computational science interests you.

To use Numpy, we first need to import the `numpy` package:

In [81]:
import numpy as np

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. 

We can initialise numpy arrays from nested Python lists, and access elements using square brackets:

In [82]:
import numpy as np

# Create a rank 1 (1D) array
a = np.array([1, 2, 3])

# Print the number of items in each dimenions of the array
print(f'Shape: {a.shape}') 

# Print the items of the array separately
print(f'Items: {a[0]}, {a[1]}, {a[2]}')

# Change the value of one of the elements in the array
# and print the array
a[0] = 5
print(f'Items: {a}')

Shape: (3,)
Items: 1, 2, 3
Items: [5 2 3]


In [83]:
import numpy as np

# Create a rank 2 (2D) array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Print the number of items in each dimenions of the array
print(f'Shape: {b.shape}')

# Print some of the items explicitly
print(f'Items: {b[0, 0]}, {b[0, 1]}, {b[1, 0]}')

Shape: (2, 3)
Items: 1, 2, 4


Numpy also provides many functions to create arrays

In [84]:
import numpy as np

# Create a 2X2 array of all zeros
a = np.zeros((2, 2))
print(a, '\n')

# Create a 1X2 array of all ones
b = np.ones((1, 2))
print(b, '\n')

# Create a 2X2 identity matrix
c = np.eye(2)
print(c, '\n')

# Create a range of numbers
d = np.arange(10)
print(d, '\n')

# Generate evenly spaced numbers of a specified interval
e = np.linspace(0, 1, 9)
print(e, '\n')

# Create a 2x2 array filled with random values
f = np.random.random((2, 2))
print(f)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[1. 0.]
 [0. 1.]] 

[0 1 2 3 4 5 6 7 8 9] 

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ] 

[[0.78190847 0.90565221]
 [0.72662892 0.36776155]]


### Array Indexing

Numpy offers several ways to index into arrays. 

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [85]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[1  2  3  4]
#  [5  6  7  8]
#  [9  10 11 12]]
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows and
# columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array:

In [86]:
print (a[0, 1], '\n')  

b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]

print(a[0, 1])

2 

77


You can mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [87]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array. Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array:

In [88]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print('Array:', row_r1, 'shape:', row_r1.shape, '\n')
print('Array:', row_r2, 'shape:', row_r2.shape, '\n')
print('Array:', row_r3, 'shape:', row_r3.shape)

Array: [5 6 7 8] shape: (4,) 

Array: [[5 6 7 8]] shape: (1, 4) 

Array: [[5 6 7 8]] shape: (1, 4)


In [89]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print('Array:', col_r1, 'shape:', col_r1.shape, '\n')
print(col_r2, 'shape:', col_r2.shape)

Array: [ 2  6 10] shape: (3,) 

[[ 2]
 [ 6]
 [10]] shape: (3, 1)


**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [90]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]], '\n')

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5] 

[1 4 5]


In [91]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]], '\n')

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2] 

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [92]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [93]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [94]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [95]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [96]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx], '\n')

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6] 

[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [97]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


## Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [98]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y, '\n')
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]] 

[[ 6.  8.]
 [10. 12.]]


In [99]:
# Elementwise difference; both produce the array
print(x - y, '\n')
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]] 

[[-4. -4.]
 [-4. -4.]]


In [100]:
# Elementwise product; both produce the array
print(x * y, '\n')
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]] 

[[ 5. 12.]
 [21. 32.]]


In [101]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y, '\n')
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [102]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [103]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w), '\n')
print(np.dot(v, w))

219 

219


In [104]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v), '\n')
print(np.dot(x, v))

[29 67] 

[29 67]


In [105]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y), '\n')
print(np.dot(x, y))

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [106]:
x = np.array([[1,2],[3,4]])

print(np.sum(x), '\n')  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0), '\n')  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1), '\n')  # Compute sum of each row; prints "[3 7]"

10 

[4 6] 

[3 7] 



Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [107]:
print(x, '\n')
print(x.T)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


In [108]:
v = np.array([[1,2,3]])
print(v, '\n')
print(v.T)

[[1 2 3]] 

[[1]
 [2]
 [3]]


## Milestone: Gaussian Elimination

In linear algebra, Gaussian elimination is an algorithm for solving systems of linear equations. It is usually understood as a sequence of operations performed on the corresponding matrix of coefficients. This method can also be used to find the rank of a matrix, to calculate the determinant of a matrix, and to calculate the inverse of an invertible square matrix.

Suppose you have a system of $n \in \mathbb{N}_{\ge1}$ linear equations and variables $x_1,x_2,\dotsb,x_n \in \mathbb{R}$:

$$ 
\begin{aligned}
a_{1,1}\cdot x_1 + a_{1,2}\cdot x_2 + \dotsb + a_{1,n}\cdot x_n  &=  b_1  \\
a_{2,1}\cdot x_1 + a_{2,2}\cdot x_2 + \dotsb + a_{2,n}\cdot x_n  &=  b_2 \\
\vdots &= \vdots \\
a_{n,1}\cdot x_1 + a_{n,2}\cdot x_2 + \dotsb + a_{n,n}\cdot x_n  &=  b_n
\end{aligned}
$$

All factors $a_{i,j}\in\mathbb{R}$ for $i,j\in1,\dotsb,n$ can be written in one matrix $A\in\dotsb^{n\times n}$ and all $b_i$ can be written as a vector $b$. You combine all $x_i$ in the same way to a vector $x$. So you can write the system of equations as :

$$ A \cdot x = b $$

For Gaussian elimination, first you write $A$ and $b$ in an augmented matrix $(A|b)$:

$$
\left(
\begin{array}{cccc|c}
a_{1,1} & a_{1,2} & \dotsb & a_{1,n} & b_1 \\
a_{2,1} & a_{2,2} & \dotsb & a_{2,n} & b_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
a_{n,1} & a_{n,2} & \dotsb & a_{n,n} & b_n \\
\end{array}\right)
$$

On this matrix you may make exactly three operations:
- Swap rows
- Add row onto another
- Multiply every factor of one row with a constant

You want to get a triangular matrix. So you subsequently eliminate one variables from the system of equations until you have a matrix like:

$$
\left(
\begin{array}{ccccc|c}
a_{1,1} & a_{1,2} & a_{1,3} & \dotsb & a_{1,n} & b_1 \\
0 & a_{2,2} & a_{3,2} & \dotsb & a_{2,n} & b_2 \\
0 & 0 & a_{3,3} & \dotsb & a_{3,n} & b_3 \\
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\
0 & 0 & \dotsb & 0 & a_{3,n} & b_n \\
\end{array}\right)
$$

Implement the Gaussian elimination and test out your implementation for the following set of equations:

$$ 
\begin{aligned}
4x_1 - 2x_2 + x_3 &= 15 \\
-3x_1 - x_2 + 4x_3 &= 8 \\
x_1 - 3x_2 + 3x_3 &= 15 \\
\end{aligned}
$$

In [109]:
import numpy as np

# Function which will implement the Gaussian elimination procedure
# This takes two arguments, A and b
def gauss(A, b):
    n = len(A)
    
    for i in range(n):
        # Divide by the diagonal element
        div = A[i, i]
        A[i, :] /= div
        b[i] /= div
       
        # Subtract from the lower rows
        for j in range(i + 1, n):
            mult = A[j, i]
            A[j,:] -= mult * A[i, :]
            b[j] -= mult * b[i]
               
    # Back-substitution
    x = np.empty(n)
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= A[i, j] * x[j]
    
    return x

A = np.array([[4, -2, 1],
               [-3, -1, 4], 
               [1, -3, 3]], float)
b = np.array([15, 8, 15], float)
print(gauss(A, b))
    

[ 2.7 -0.1  4. ]


Additionally, NumPy has methods to directly solve a system of linear equations. Compare the result with the one provided by Gaussian elimination:

In [110]:
import numpy as np

A = np.array([[4, -2, 1],
               [-3, -1, 4],
               [1, -3, 3]], float)
b = np.array([15, 8, 15], float)

print(np.linalg.solve(A, b))

[ 2.7 -0.1  4. ]


Apart from Gaussian elimination, we can also look at LU (lower-upper) decomposition. The SciPy module has an implementation of LU decomposition which you can use (such that $PA = LU$):

In [111]:
from scipy import linalg

A = np.array([[4, -2, 1],
               [-3, -1, 4], 
               [1, -3, 3]], float)

lu = linalg.lu(A)
print('P\n', lu[0], '\n')
print('L\n', lu[1], '\n')
print('U\n', lu[2])

P
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

L
 [[ 1.    0.    0.  ]
 [-0.75  1.    0.  ]
 [ 0.25  1.    1.  ]] 

U
 [[ 4.   -2.    1.  ]
 [ 0.   -2.5   4.75]
 [ 0.    0.   -2.  ]]


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [112]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix  vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [113]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)               

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [114]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [115]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though x has shape `(4, 3)` and v has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:
    
1. Line up shapes from the right. Think of shapes as written in a column, lined up at the end. Example:

    * A.shape = (3, 1)
    * B.shape = (4,) -> think of it as (1,4)
    * Lined up: A: (3,1), B: (1,4)

2. For each position, sizes must be either equal or 1. If not broadcasting fails. Example:

    1. (3,1) with (1,4)
        * position 1 (from right): 1 vs 4, one is 1, therefore OK.
        * position 2: 3 vs 1, one is 1, therefore OK.

    2. (2,3) with (2,4)<br>
        * Position 1: 3 vs 4, not equal, none is 1, therefore Error.

3. If shapes have different lenghts, pad the shorter one with leading 1s. Example: (5,3) with (3,)

    * (3,) -> treat as (1,3)
    * Now compare (5,3) and (1,3)

4. A dimension of size 1 is stretchy. It gets repeated to match the other size on that axis. Example: (5,3) and (1,3), results in a shape of (5,3). The first axis of the second array is 1, so it is repeated 5 times.

5. The output size in each dimension is the bigger of the two. After alignment, take the max along each axis. Example (3,1) and (1,4), results in (3,4).

6. Scalars work with anything. A scalar has shape (), it just stretches to whatever you have. Example

    * A.shape = () e.g. A = 5
    * B.shape = (2,3)
    * A + B results in a shape (2,3); 5 is added to every element.

If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [116]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [117]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [118]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [119]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [120]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

Additionally, you can find a lot of useful exercises (which can be used for reference) [here](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.md)

***
Back to [index](index.ipynb) page